[package]
name = "vag2mqtt"
description = "Connect Volkswagen Group vehicles to MQTT"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license-file.workspace = true
default-run = "vag2mqtt"

[lints]
workspace = true

[dependencies]
vag2mqtt-admin.workspace = true
vag2mqtt-connector-audi.workspace = true
vag2mqtt-domain.workspace = true
vag2mqtt-persistence.workspace = true
vag2mqtt-runtime.workspace = true

anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
