//! Identity types: account identifier, VIN, brand and the connector classification enums.

use std::fmt;
use std::str::FromStr;

use serde::{Deserialize, Serialize};

use crate::error::DomainError;

/// Opaque identifier of an account.
///
/// Generated by the persistence layer (a UUID v4 string). The domain only guarantees that the
/// value is non-empty and safe to embed in an MQTT topic: ASCII letters, digits, `_` and `-`.
#[derive(Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct AccountId(String);

impl AccountId {
    /// Wraps and validates an identifier.
    pub fn new(id: impl Into<String>) -> Result<Self, DomainError> {
        let id = id.into();
        if id.is_empty() {
            return Err(DomainError::InvalidAccountId { reason: "empty" });
        }
        if !id
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'-')
        {
            return Err(DomainError::InvalidAccountId {
                reason: "only ASCII letters, digits, '_' and '-' are allowed",
            });
        }
        Ok(Self(id))
    }

    /// The identifier as a string slice.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for AccountId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "AccountId({})", self.0)
    }
}

impl fmt::Display for AccountId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl FromStr for AccountId {
    type Err = DomainError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::new(s)
    }
}

impl TryFrom<String> for AccountId {
    type Error = DomainError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::new(value)
    }
}

impl From<AccountId> for String {
    fn from(id: AccountId) -> Self {
        id.0
    }
}

/// A vehicle identification number.
///
/// Seventeen characters from `[A-HJ-NPR-Z0-9]`; lower case input is upper cased on parse.
/// `Display` prints the full VIN because topics need it. `Debug` prints only the last four
/// characters, so a VIN never reaches a log line through a derived `Debug`.
#[derive(Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct Vin(String);

impl Vin {
    /// Length of a VIN in characters.
    pub const LEN: usize = 17;

    /// Parses and normalises a VIN.
    pub fn new(vin: impl AsRef<str>) -> Result<Self, DomainError> {
        let normalised = vin.as_ref().trim().to_ascii_uppercase();
        if normalised.chars().count() != Self::LEN {
            return Err(DomainError::InvalidVin {
                reason: "must be exactly 17 characters",
            });
        }
        if !normalised.bytes().all(Self::is_vin_byte) {
            return Err(DomainError::InvalidVin {
                reason: "only digits and the letters A-Z without I, O and Q are allowed",
            });
        }
        Ok(Self(normalised))
    }

    fn is_vin_byte(b: u8) -> bool {
        b.is_ascii_digit() || (b.is_ascii_uppercase() && !matches!(b, b'I' | b'O' | b'Q'))
    }

    /// The full VIN.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// The redacted form for logs: an ellipsis and the last four characters.
    pub fn short(&self) -> String {
        format!("…{}", &self.0[self.0.len() - 4..])
    }
}

impl fmt::Debug for Vin {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Vin({})", self.short())
    }
}

impl fmt::Display for Vin {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl FromStr for Vin {
    type Err = DomainError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::new(s)
    }
}

impl TryFrom<String> for Vin {
    type Error = DomainError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::new(value)
    }
}

impl From<Vin> for String {
    fn from(vin: Vin) -> Self {
        vin.0
    }
}

/// A Volkswagen Group brand.
///
/// Only [`Brand::Audi`] has a connector in the first release. The other variants exist so that
/// persistence and the UI need no change when WP-22 adds them.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Brand {
    /// Audi.
    Audi,
    /// Volkswagen.
    Volkswagen,
    /// Škoda.
    Skoda,
    /// Seat.
    Seat,
    /// Cupra.
    Cupra,
}

impl Brand {
    /// Every variant, in declaration order.
    pub const ALL: &'static [Brand] = &[
        Brand::Audi,
        Brand::Volkswagen,
        Brand::Skoda,
        Brand::Seat,
        Brand::Cupra,
    ];

    /// The brand as a lower case identifier, identical to its serde form.
    pub fn as_str(self) -> &'static str {
        match self {
            Brand::Audi => "audi",
            Brand::Volkswagen => "volkswagen",
            Brand::Skoda => "skoda",
            Brand::Seat => "seat",
            Brand::Cupra => "cupra",
        }
    }
}

impl fmt::Display for Brand {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// How a connector obtains its data (requirements section 4.4).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DataSourceKind {
    /// Fetch on demand from a manufacturer backend; near real time, commands may be possible.
    LiveApi,
    /// Download pre-generated data sets that the user configured in a portal; read only.
    Export,
}

impl DataSourceKind {
    /// Every variant, in declaration order.
    pub const ALL: &'static [DataSourceKind] = &[DataSourceKind::LiveApi, DataSourceKind::Export];
}

/// The propulsion of a vehicle, derived from the manufacturer's car type.
///
/// It tells consumers which categories are *expected* to be supported; the truth per value is
/// still the [`Reading`](crate::Reading) state.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Drivetrain {
    /// Battery electric.
    Electric,
    /// Petrol, diesel or gas, no traction battery.
    Combustion,
    /// Both a traction battery and a fuel tank.
    Hybrid,
    /// Not delivered or not recognised.
    Unknown,
}

impl Drivetrain {
    /// Every variant, in declaration order.
    pub const ALL: &'static [Drivetrain] = &[
        Drivetrain::Electric,
        Drivetrain::Combustion,
        Drivetrain::Hybrid,
        Drivetrain::Unknown,
    ];
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE_VIN: &str = "WAUZZZ0000000TEST";

    #[test]
    fn vin_is_uppercased_and_trimmed() {
        let vin = Vin::new(" wauzzz0000000test ").unwrap();
        assert_eq!(vin.as_str(), SAMPLE_VIN);
        assert_eq!(vin.to_string(), SAMPLE_VIN);
    }

    #[test]
    fn vin_rejects_wrong_length() {
        assert!(matches!(
            Vin::new("WAUZZZ000000TEST"),
            Err(DomainError::InvalidVin { .. })
        ));
        assert!(matches!(
            Vin::new("WAUZZZ0000000TEST1"),
            Err(DomainError::InvalidVin { .. })
        ));
    }

    #[test]
    fn vin_rejects_i_o_q_and_symbols() {
        for bad in [
            "WAUZZZ0000000TESI",
            "WAUZZZ0000000TESO",
            "WAUZZZ0000000TESQ",
            "WAUZZZ0000000TES-",
        ] {
            assert!(Vin::new(bad).is_err(), "{bad} must be rejected");
        }
    }

    #[test]
    fn vin_debug_shows_only_the_last_four_characters() {
        let vin = Vin::new(SAMPLE_VIN).unwrap();
        let debug = format!("{vin:?}");
        assert_eq!(debug, "Vin(…TEST)");
        assert!(!debug.contains("WAUZZZ"));
        assert_eq!(vin.short(), "…TEST");
    }

    #[test]
    fn vin_serde_round_trip_validates() {
        let vin = Vin::new(SAMPLE_VIN).unwrap();
        let json = serde_json::to_string(&vin).unwrap();
        assert_eq!(json, format!("\"{SAMPLE_VIN}\""));
        let back: Vin = serde_json::from_str(&json).unwrap();
        assert_eq!(back, vin);
        assert!(serde_json::from_str::<Vin>("\"short\"").is_err());
    }

    #[test]
    fn account_id_accepts_uuid_like_values_and_rejects_topic_unsafe_ones() {
        assert!(AccountId::new("3f2504e0-4f89-11d3-9a0c-0305e82c3301").is_ok());
        assert!(AccountId::new("acc_1").is_ok());
        assert!(AccountId::new("").is_err());
        assert!(AccountId::new("a/b").is_err());
        assert!(AccountId::new("a b").is_err());
        assert!(AccountId::new("a+b").is_err());
        assert!(AccountId::new("ä").is_err());
    }

    #[test]
    fn brand_display_matches_serde() {
        for brand in Brand::ALL {
            let json = serde_json::to_string(brand).unwrap();
            assert_eq!(json, format!("\"{brand}\""));
        }
    }
}
