[package]
name = "vag2mqtt-connector-audi"
description = "Audi connector for VAG2MQTT"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
vag2mqtt-connector-api.workspace = true
vag2mqtt-domain.workspace = true
